import jsPDF from "jspdf";

type PDFIdentity = {
  name: string;
  headline: string | null;
  bio: string | null;
  type: string;
  profession?: string | null;
  tags?: string[];
};

type PDFBranch = {
  headline: string;
  description: string;
  cta: string;
  proof: string | null;
};

type PDFOption = {
  label: string;
  branch: PDFBranch | null;
};

type PDFCapsule = {
  title: string;
  objective: string;
  options: PDFOption[];
};

type PDFProject = {
  title: string;
  description: string;
  year: number | null;
};

type PDFTestimonial = {
  author: string;
  content: string;
  role: string | null;
  company: string | null;
};

type GeneratePDFParams = {
  identity: PDFIdentity;
  capsules: PDFCapsule[];
  projects: PDFProject[];
  testimonials: PDFTestimonial[];
};

const COLORS = {
  primary: [99, 102, 241] as [number, number, number],     // indigo
  dark: [24, 24, 27] as [number, number, number],           // zinc-900
  text: [63, 63, 70] as [number, number, number],           // zinc-700
  muted: [113, 113, 122] as [number, number, number],       // zinc-500
  light: [244, 244, 245] as [number, number, number],       // zinc-100
  white: [255, 255, 255] as [number, number, number],
  accent: [139, 92, 246] as [number, number, number],       // violet
};

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;

function checkPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - 25) {
    doc.addPage();
    return 25;
  }
  return y;
}

export function generatePortfolioPDF({ identity, capsules, projects, testimonials }: GeneratePDFParams) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  let y = 0;

  // ══════════════ COVER PAGE ══════════════
  // Background
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");

  // Accent bar at top
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, PAGE_W, 4, "F");

  // Name
  y = 80;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  doc.setTextColor(...COLORS.white);
  doc.text(identity.name, PAGE_W / 2, y, { align: "center" });

  // Type badge
  y += 14;
  const typeLabels: Record<string, string> = {
    FREELANCER: "Freelancer",
    AGENCY: "Agence",
    CREATOR: "Créateur",
    STARTUP: "Startup",
  };
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.accent);
  doc.text(typeLabels[identity.type] || identity.type, PAGE_W / 2, y, { align: "center" });

  if (identity.profession?.trim()) {
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(161, 161, 170);
    doc.text(identity.profession.trim(), PAGE_W / 2, y, { align: "center" });
  }
  if (identity.tags && identity.tags.length > 0) {
    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text(identity.tags.slice(0, 12).join(" · "), PAGE_W / 2, y, { align: "center" });
  }

  // Headline
  if (identity.headline) {
    y += 12;
    doc.setFontSize(14);
    doc.setTextColor(161, 161, 170); // zinc-400
    const headLines = doc.splitTextToSize(identity.headline, CONTENT_W - 20);
    doc.text(headLines, PAGE_W / 2, y, { align: "center" });
    y += headLines.length * 6;
  }

  // Bio
  if (identity.bio) {
    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.muted);
    const bioLines = doc.splitTextToSize(identity.bio, CONTENT_W - 30);
    doc.text(bioLines, PAGE_W / 2, y, { align: "center" });
    y += bioLines.length * 5;
  }

  // Decorative line
  y += 20;
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(PAGE_W / 2 - 20, y, PAGE_W / 2 + 20, y);

  // Generated by Faymoos
  doc.setFontSize(8);
  doc.setTextColor(82, 82, 91); // zinc-600
  doc.text("Portfolio généré par Faymoos", PAGE_W / 2, PAGE_H - 20, { align: "center" });
  doc.text(new Date().toLocaleDateString("fr-FR", { year: "numeric", month: "long", day: "numeric" }), PAGE_W / 2, PAGE_H - 14, { align: "center" });

  // ══════════════ CAPSULES PAGES ══════════════
  for (const capsule of capsules) {
    doc.addPage();

    // Page background
    doc.setFillColor(...COLORS.white);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");

    // Header bar
    doc.setFillColor(...COLORS.dark);
    doc.rect(0, 0, PAGE_W, 50, "F");
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 50, PAGE_W, 2, "F");

    // Capsule title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.accent);
    doc.text(capsule.title.toUpperCase(), PAGE_W / 2, 22, { align: "center" });

    // Objective
    doc.setFontSize(16);
    doc.setTextColor(...COLORS.white);
    const objLines = doc.splitTextToSize(capsule.objective, CONTENT_W - 10);
    doc.text(objLines, PAGE_W / 2, 34, { align: "center" });

    y = 62;

    // Options
    for (let i = 0; i < capsule.options.length; i++) {
      const opt = capsule.options[i];
      y = checkPage(doc, y, 50);

      // Option card
      doc.setFillColor(...COLORS.light);
      doc.roundedRect(MARGIN, y, CONTENT_W, 12, 3, 3, "F");

      // Option number
      doc.setFillColor(...COLORS.primary);
      doc.roundedRect(MARGIN + 3, y + 2.5, 7, 7, 2, 2, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.white);
      doc.text(String(i + 1), MARGIN + 6.5, y + 7.2, { align: "center" });

      // Option label
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...COLORS.dark);
      doc.text(opt.label, MARGIN + 14, y + 8);

      y += 16;

      // Branch content
      if (opt.branch) {
        y = checkPage(doc, y, 40);

        // Headline
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(...COLORS.dark);
        const hlLines = doc.splitTextToSize(opt.branch.headline, CONTENT_W - 10);
        doc.text(hlLines, MARGIN + 5, y);
        y += hlLines.length * 6 + 3;

        // Description
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...COLORS.text);
        const descLines = doc.splitTextToSize(opt.branch.description, CONTENT_W - 10);
        y = checkPage(doc, y, descLines.length * 4.5 + 5);
        doc.text(descLines, MARGIN + 5, y);
        y += descLines.length * 4.5 + 4;

        // Proof
        if (opt.branch.proof) {
          y = checkPage(doc, y, 20);
          doc.setFillColor(237, 233, 254); // violet-100
          const proofLines = doc.splitTextToSize(opt.branch.proof, CONTENT_W - 22);
          const proofH = proofLines.length * 4.5 + 10;
          doc.roundedRect(MARGIN + 5, y, CONTENT_W - 10, proofH, 2, 2, "F");

          doc.setFont("helvetica", "bold");
          doc.setFontSize(7);
          doc.setTextColor(...COLORS.accent);
          doc.text("PREUVE", MARGIN + 10, y + 5);

          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.setTextColor(...COLORS.text);
          doc.text(proofLines, MARGIN + 10, y + 10);
          y += proofH + 4;
        }

        // CTA
        y = checkPage(doc, y, 12);
        doc.setFillColor(...COLORS.primary);
        const ctaW = Math.min(doc.getTextWidth(opt.branch.cta) + 16, CONTENT_W - 10);
        doc.roundedRect(MARGIN + 5, y, ctaW, 10, 3, 3, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(...COLORS.white);
        doc.text(opt.branch.cta, MARGIN + 5 + ctaW / 2, y + 6.5, { align: "center" });
        y += 16;
      }

      // Separator between options
      if (i < capsule.options.length - 1) {
        y = checkPage(doc, y, 8);
        doc.setDrawColor(228, 228, 231); // zinc-200
        doc.setLineWidth(0.3);
        doc.line(MARGIN + 10, y, PAGE_W - MARGIN - 10, y);
        y += 6;
      }
    }
  }

  // ══════════════ PORTFOLIO PAGE ══════════════
  if (projects.length > 0) {
    doc.addPage();
    doc.setFillColor(...COLORS.white);
    doc.rect(0, 0, PAGE_W, PAGE_H, "F");

    // Section header
    doc.setFillColor(...COLORS.primary);
    doc.rect(MARGIN, 25, 3, 14, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(...COLORS.dark);
    doc.text("Portfolio", MARGIN + 8, 36);

    y = 48;

    for (const p of projects) {
      y = checkPage(doc, y, 28);

      // Project card
      doc.setFillColor(...COLORS.light);
      const titleLines = doc.splitTextToSize(p.title, CONTENT_W - 30);
      const descLines = doc.splitTextToSize(p.description, CONTENT_W - 16);
      const cardH = titleLines.length * 5 + descLines.length * 4.5 + 14;

      doc.roundedRect(MARGIN, y, CONTENT_W, cardH, 3, 3, "F");

      // Accent bar
      doc.setFillColor(...COLORS.primary);
      doc.rect(MARGIN, y, 3, cardH, "F");

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...COLORS.dark);
      doc.text(titleLines, MARGIN + 8, y + 7);

      // Year
      if (p.year) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.muted);
        doc.text(String(p.year), PAGE_W - MARGIN - 5, y + 7, { align: "right" });
      }

      // Description
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.text);
      doc.text(descLines, MARGIN + 8, y + titleLines.length * 5 + 10);

      y += cardH + 5;
    }
  }

  // ══════════════ TESTIMONIALS PAGE ══════════════
  if (testimonials.length > 0) {
    y = checkPage(doc, y, 60);
    if (y < 50) {
      // We're on a new page already
    } else if (projects.length === 0) {
      doc.addPage();
      doc.setFillColor(...COLORS.white);
      doc.rect(0, 0, PAGE_W, PAGE_H, "F");
      y = 25;
    }

    y = checkPage(doc, y, 30);

    // Add spacing if continuing on same page
    if (y > 50) y += 10;

    // Section header
    doc.setFillColor(...COLORS.accent);
    doc.rect(MARGIN, y, 3, 14, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(...COLORS.dark);
    doc.text("Témoignages", MARGIN + 8, y + 11);

    y += 22;

    for (const t of testimonials) {
      y = checkPage(doc, y, 30);

      // Quote icon
      doc.setFont("helvetica", "bold");
      doc.setFontSize(24);
      doc.setTextColor(199, 194, 213); // faded quote
      doc.text("\u201C", MARGIN + 3, y + 6);

      // Content
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.text);
      const contentLines = doc.splitTextToSize(t.content, CONTENT_W - 16);
      doc.text(contentLines, MARGIN + 12, y + 2);
      y += contentLines.length * 4.5 + 4;

      // Author info
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.dark);
      const authorLine = t.author;
      if (t.role || t.company) {
        doc.text(authorLine, MARGIN + 12, y);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...COLORS.muted);
        const meta = [t.role, t.company].filter(Boolean).join(" · ");
        doc.text(` — ${meta}`, MARGIN + 12 + doc.getTextWidth(authorLine + " "), y);
      } else {
        doc.text(authorLine, MARGIN + 12, y);
      }

      y += 10;

      // Separator
      doc.setDrawColor(228, 228, 231);
      doc.setLineWidth(0.2);
      doc.line(MARGIN + 12, y - 4, PAGE_W - MARGIN - 10, y - 4);
    }
  }

  // Save
  const safeName = identity.name.replace(/[^a-zA-Z0-9]/g, "-").replace(/-+/g, "-");
  doc.save(`${safeName}-portfolio.pdf`);
}
